export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const ADDCOUNTER = "ADDCOUNTER";
export const DELCOUNTER = "DELCOUNTER";
export const ADD_COUNTER_RECORD = "ADDCOUNTERRECORD";
export const DEL_COUNTER_RECORD = "DELCOUNTERRECORD";
